[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_ADMIN_API_BASE_URL = "https://ryde-admin-api.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
